# Generated by Django 5.2 on 2025-06-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_submission_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-updated_at']},
        ),
    ]
