# Generated by Django 5.2 on 2025-06-24 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_submission_options'),
        ('scope', '0008_migrate_scope_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='scope_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', related_query_name='exam', to='scope.scope'),
        ),
    ]
