# Generated by Django 5.2 on 2025-06-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_exam_scope_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='scope_id',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='scope_type',
        ),
    ]
