# Generated by Django 5.2 on 2025-06-24 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_exam_scope_id_remove_exam_scope_type'),
        ('scope', '0008_migrate_scope_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='scope_field',
        ),
        migrations.AddField(
            model_name='exam',
            name='scope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exams', related_query_name='exam', to='scope.scope'),
            preserve_default=False,
        ),
    ]
