# Generated by Django 5.2 on 2025-07-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_exam_scope_field_exam_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('solving', 'Solving'), ('exited_unexpectedly', 'Exited Unexpectedly'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
