# Generated by Django 5.2 on 2025-07-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('exited_unexpectedly', 'Exited Unexpectedly'), ('completed', 'Completed')], default='exited_unexpectedly', max_length=20),
        ),
    ]
