# Generated by Django 5.2 on 2025-07-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_alter_submission_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at']},
        ),
    ]
