# Generated by Django 5.2 on 2025-07-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_exam_options'),
        ('scope', '0009_remove_lesson_chapter_remove_unit_textbook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='scope',
        ),
        migrations.AddField(
            model_name='exam',
            name='scope',
            field=models.ManyToManyField(related_name='exams', related_query_name='exam', to='scope.scope'),
        ),
    ]
