# Generated by Django 5.2 on 2025-07-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_remove_exam_scope_exam_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='scope',
            new_name='scopes',
        ),
    ]
