# Generated by Django 5.2 on 2025-08-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_rename_scope_exam_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
