# Generated by Django 5.2 on 2025-04-10 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("caption", models.TextField()),
                ("ccover", models.ImageField(upload_to="")),
                ("in_scope_order", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["unit__in_scope_order", "in_scope_order"],
            },
        ),
        migrations.CreateModel(
            name="TextBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("caption", models.TextField()),
                ("ccover", models.ImageField(upload_to="")),
                ("in_scope_order", models.PositiveSmallIntegerField()),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        related_query_name="lesson",
                        to="scope.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["chapter__in_scope_order", "in_scope_order"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("caption", models.TextField()),
                ("ccover", models.ImageField(upload_to="")),
                ("in_scope_order", models.PositiveSmallIntegerField()),
                (
                    "textbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        related_query_name="unit",
                        to="scope.textbook",
                    ),
                ),
            ],
            options={
                "ordering": ["in_scope_order"],
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                related_query_name="chapter",
                to="scope.unit",
            ),
        ),
    ]
