# Generated by Django 5.2 on 2025-04-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scope", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="ccover",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="ccover",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="ccover",
        ),
        migrations.AddField(
            model_name="chapter",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="lesson",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="unit",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="caption",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="in_scope_order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="caption",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="in_scope_order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="unit",
            name="caption",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="unit",
            name="in_scope_order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
