# Generated by Django 5.2 on 2025-04-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scope", "0002_remove_chapter_ccover_remove_lesson_ccover_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("unit", "in_scope_order")},
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("chapter", "in_scope_order")},
        ),
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together={("textbook", "in_scope_order")},
        ),
    ]
