# Generated by Django 5.2 on 2025-04-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scope", "0003_alter_chapter_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(
                fields=("unit", "in_scope_order"), name="unique_chapter_order_in_unit"
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("chapter", "in_scope_order"),
                name="unique_lesson_order_in_chapter",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                fields=("textbook", "in_scope_order"),
                name="unique_unit_order_in_textbook",
            ),
        ),
    ]
