# Generated by Django 5.2 on 2025-06-24 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scope", "0006_alter_chapter_title_alter_lesson_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("caption", models.TextField(blank=True, default="")),
                ("cover", models.ImageField(blank=True, null=True, upload_to="")),
                ("slug", models.SlugField(editable=False, max_length=512, unique=True)),
                ("in_scope_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Textbook"),
                            (1, "Unit"),
                            (2, "Chapter"),
                            (3, "Lesson"),
                        ],
                        default=0,
                        editable=False,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        related_query_name="child",
                        to="scope.scope",
                    ),
                ),
            ],
            options={
                "ordering": ["in_scope_order"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("parent__isnull", False)),
                        fields=("parent", "in_scope_order"),
                        name="unique_scope_order_in_parent",
                    ),
                    models.UniqueConstraint(
                        fields=("parent", "title"), name="unique_title_of_same_parent"
                    ),
                ],
            },
        ),
    ]
