# Generated by Django 5.2 on 2025-06-24 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scope", "0008_migrate_scope_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chapter",
        ),
        migrations.DeleteModel(
            name="Lesson",
        ),
        migrations.DeleteModel(
            name="TextBook",
        ),
        migrations.DeleteModel(
            name="Unit",
        ),
    ]
