# Generated by Django 5.2 on 2025-09-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0009_remove_lesson_chapter_remove_unit_textbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
