# Generated by Django 5.2 on 2025-10-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0010_scope_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Textbook'), (1, 'Unit'), (2, 'Chapter'), (3, 'Lesson')], default=0),
        ),
    ]
