# Generated by Django 5.2 on 2025-06-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0006_alter_chapter_title_alter_lesson_title_and_more'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chapters',
            field=models.ManyToManyField(to='scope.chapter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lessons',
            field=models.ManyToManyField(to='scope.lesson'),
        ),
        migrations.AddField(
            model_name='profile',
            name='textbooks',
            field=models.ManyToManyField(to='scope.textbook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='units',
            field=models.ManyToManyField(to='scope.unit'),
        ),
    ]
