# Generated by Django 5.2 on 2025-06-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='chapters',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='textbooks',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='units',
        ),
    ]
