# Generated by Django 5.2 on 2025-06-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_profile",
            "0004_remove_profile_chapters_remove_profile_textbooks_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="lessons",
        ),
        migrations.AddField(
            model_name="profile",
            name="scopes",
            field=models.ManyToManyField(to="scope.scope"),
        ),
    ]
