# Generated by Django 5.2 on 2025-07-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0009_remove_lesson_chapter_remove_unit_textbook_and_more'),
        ('user_profile', '0005_remove_profile_lessons_profile_scopes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='scopes',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='scope.scope'),
        ),
    ]
