# Generated by Django 5.2 on 2025-04-10 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scope", "0004_alter_chapter_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "figure",
                    models.ImageField(blank=True, null=True, upload_to="problems/"),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Easy"),
                            (2, "Medium"),
                            (3, "Hard"),
                            (4, "Extra hard"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        related_query_name="problem",
                        to="scope.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["difficulty", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "figure",
                    models.ImageField(blank=True, null=True, upload_to="choices/"),
                ),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        related_query_name="choice",
                        to="problem.problem",
                    ),
                ),
            ],
        ),
    ]
