# Generated by Django 5.2 on 2025-06-24 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
        ('scope', '0008_migrate_scope_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='scope',
            field=models.ForeignKey(limit_choices_to={'level': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', related_query_name='problem', to='scope.scope'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', related_query_name='problem', to='scope.lesson'),
        ),
    ]
