# Generated by Django 5.2 on 2025-06-24 07:47

from django.db import migrations, transaction
from django.utils.text import slugify


def migrate_problems_to_scope(apps, schema_editor):
    with transaction.atomic():
        Scope = apps.get_model("scope", "Scope")
        Problem = apps.get_model("problem", "Problem")

        scope_lessons = Scope.objects.filter(level=3)
        problems = Problem.objects.select_related("lesson")

        scope_lessons_slug_id_map = {}

        for lesson in scope_lessons:
            scope_lessons_slug_id_map[lesson.slug] = lesson

        for problem in problems:
            key = slugify(f"Lesson {problem.lesson.title}")
            problem.scope = scope_lessons_slug_id_map[key]
            problem.save()


class Migration(migrations.Migration):
    dependencies = [
        ("problem", "0002_problem_scope_alter_problem_lesson"),
    ]

    operations = [migrations.RunPython(migrate_problems_to_scope)]
