# Generated by Django 5.2 on 2025-06-24 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_migrate_problems_to_scope'),
        ('scope', '0008_migrate_scope_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='problem',
            name='scope',
            field=models.ForeignKey(default=1, limit_choices_to={'level': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='problems', related_query_name='problem', to='scope.scope'),
            preserve_default=False,
        ),
    ]
