# Generated by Django 5.2 on 2025-07-21 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_remove_problem_lesson_alter_problem_scope'),
        ('scope', '0009_remove_lesson_chapter_remove_unit_textbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='scope',
            field=models.ForeignKey(limit_choices_to={'level': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='problems_set', related_query_name='problem', to='scope.scope'),
        ),
    ]
