# Generated by Django 5.2 on 2025-09-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_alter_problem_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
