# Generated by Django 5.2 on 2025-10-01 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0007_alter_problem_figure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="figure",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="choices/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg", "png", "jpg"]
                    )
                ],
            ),
        ),
    ]
