# Generated by Django 5.2 on 2025-10-11 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_exams_per_week', models.PositiveSmallIntegerField(default=3)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('exams_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Tracker',
                'verbose_name_plural': 'Exam Trackers',
                'db_table': 'exam_trackers',
                'ordering': ['user'],
            },
        ),
    ]
