# Generated by Django 5.2 on 2025-10-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtracker',
            name='week_start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
