# Generated by Django 5.2 on 2025-10-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_examtracker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtracker',
            name='week_start',
            field=models.DateField(),
        ),
    ]
