# Generated by Django 5.2 on 2025-10-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_examtracker_week_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examtracker',
            old_name='week_end',
            new_name='next_week_end',
        ),
    ]
