# Generated by Django 5.2 on 2025-10-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_week_end_examtracker_next_week_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examtracker',
            old_name='next_week_end',
            new_name='next_week_start',
        ),
    ]
