# Generated by Django 5.2 on 2025-10-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_rename_next_week_end_examtracker_next_week_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtracker',
            name='next_week_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
